_target_: adjoint_sampling.components.controllers.OurTensorProductScoreModel
in_node_features: 74
in_edge_features: 4 
ns: 32
nv: 8
sigma_embed_dim: 32
sigma_min: 0.0314
sigma_max: 3.14
num_conv_layers: 4
max_radius: 5.0
radius_embed_dim: 50
# scale_by_sigma: false  # we scale outside of the network, if necessary, interacts with ${use_AM_SDE}
use_second_order_repr: false
residual: true
batch_norm: true
